### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by Vicente015** [garethbjohnson/gutendex#33]
Hi, I'm using your API for a project and it was working fine until now, I keep getting CORS errors, at first I thought it was my fault but I just checked the commits and in the last commit you changed some CORS variable, so maybe that's why?

![imagen](https://github.com/garethbjohnson/gutendex/assets/33096355/6ac5a9fb-4db7-41cc-a8b0-b9ada85f2198)

**Comment by garethbjohnson** [comment]
Hi, sorry for the bug, and thank you for letting me know!

I think the issue was caused by a combination of
1. that CORS variable change
2. a deployment failure on my server due to an incompatible Python version

I spun up a replacement server with a newer version of Python, and I think that will fix the problem when domain name servers point `gutendex.com` to the new Gutendex server.

Please try again and let me know if you still have issues.

**Comment by Vicente015** [comment]
It's working perfectly now, thank you! :smile:
