### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by MohitNN** [garethbjohnson/gutendex#37]
Getting error 500

**Comment by garethbjohnson** [comment]
Thank you for reporting this. I assume you meant `gutendex.com` rather than a self-hosted server, because there has been intermittent downtime on the `gutendex.com` server lately, maybe due to high traffic. I have now added an automatic restart script which I expect to reduce the durations of downtime. Please let me know if you experience another error lasting more than a couple of minutes.
